import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useEffect } from "react";
import styles from "../styles/Home.module.css";

var mapboxgl = require("mapbox-gl/dist/mapbox-gl.js");

mapboxgl.accessToken = 'pk.eyJ1IjoianlhbyIsImEiOiJja3pzN3R3aHk3MHlqMm5waGRhNGNqNmlzIn0.BhADvRhEN-CrMSEtV1GaQA';

const Home: NextPage = () => {
  


  useEffect(() => {
    const map = new mapboxgl.Map({
      style: 'mapbox://styles/mapbox/dark-v10',
      center: [151.209, -33.8688],
      zoom: 15.5,
      pitch: 60,
      bearing: -17.6,
      container: 'mapbox',
      antialias: true
      });

      map.addControl(new mapboxgl.NavigationControl())
       
      map.on('load', () => {
      // Insert the layer beneath any symbol layer.
      const layers = map.getStyle().layers;
      const labelLayerId = layers.find(
      (layer) => layer.type === 'symbol' && layer.layout['text-field']
      ).id;
       
      // The 'building' layer in the Mapbox Streets
      // vector tileset contains building height data
      // from OpenStreetMap.
      map.addLayer(
      {
      'id': 'add-3d-buildings',
      'source': 'composite',
      'source-layer': 'building',
      'filter': ['==', 'extrude', 'true'],
      'type': 'fill-extrusion',
      'minzoom': 15,
      'paint': {
      'fill-extrusion-color': '#aaa',
       
      // Use an 'interpolate' expression to
      // add a smooth transition effect to
      // the buildings as the user zooms in.
      'fill-extrusion-height': [
      'interpolate',
      ['linear'],
      ['zoom'],
      15,
      0,
      15.05,
      ['get', 'height']
      ],
      'fill-extrusion-base': [
      'interpolate',
      ['linear'],
      ['zoom'],
      15,
      0,
      15.05,
      ['get', 'min_height']
      ],
      'fill-extrusion-opacity': 0.6
      }
      },
      labelLayerId
      );
      });
    
  }, []);

  return (
    <div className="flex items-center justify-center min-h-screen">
      <Head>
        <title>Mapbox Playgroundr</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
      <div id="mapbox" className="w-screen h-screen" />

      </main>
    </div>
  );
};

export default Home;
